name: RegionPreserve
main: com.joshargent.RegionPreserve.RegionPreservePlugin
version: 1.5.0
commands:
  rp:
    description: Region Protection main command
    usage: /<command>
    permission: rp.edit
permissions:
    rp.edit:
        description: Allows you to create or delete RegionPreserve regions
        default: op
    rp.build.*:
        description: Allows you to build in all RegionPreserve regions
        default: op